### ISSUE TITLE
Sdpaint error

### ISSUE THREAD

**Issue by lazerhawk5000** [houseofsecrets/SdPaint#12]
im running a 3090 with this i installed it inside my automic1111 directory - enabled control net to run scripts,  set it to run in api mode, updated control net, verified scribble model,  running into this error "venv "C:\Super_SD\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI

automic111 terminal error -----------------------------------------------------------------------------------
Launching Web UI with arguments: --no-half --api
No module 'xformers'. Proceeding without it.
python_server_full_path:  C:\Super_SD\stable-diffusion-webui\extensions\Auto-Photoshop-StableDiffusion-Plugin\server/python_server
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Loading weights [9aba26abdf] from C:\Super_SD\stable-diffusion-webui\models\Stable-diffusion\deliberate_v2.safetensors
Creating model from config: C:\Super_SD\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(9): advntr, bad-artist-anime, bad-artist, bad-hands-5, bad-image-v2-39000, EasyNegative, emb-rrf2, eonn, ng_deepnegative_v1_75t
Textual inversion embeddings skipped(3): nartfixer, nfixer, nrealfixer
Model loaded in 2.9s (create model: 0.5s, apply weights to model: 0.6s, move model to device: 1.0s, load textual inversion embeddings: 0.8s).
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[ControlNet] warning: using deprecated '/controlnet/txt2img' route
[ControlNet] warning: consider using the '/sdapi/v1/txt2img' route with the 'alwayson_scripts' json property instead
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 104, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Super_SD\stable-diffusion-webui\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Super_SD\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Super_SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 99, in controlnet_txt2img
    return self.controlnet_any2img(
  File "C:\Super_SD\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 115, in controlnet_any2img
    alwayson_scripts = dict(any2img_request.alwayson_scripts)
AttributeError: 'ControlNetStableDiffusionProcessingTxt2Img' object has no attribute 'alwayson_scripts'"
-----------------------------------------------------------------------------------------------------------------------------------------
sdpaint error 

WARNING: You are using pip version 22.0.4; however, version 23.1 is available.
You should consider upgrading via the 'C:\Super_SD\sd_livepaint\SdPaint\venv\Scripts\python.exe -m pip install --upgrade pip' command.
pygame 2.3.0 (SDL 2.24.2, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Super_SD\sd_livepaint\SdPaint\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\andre\anaconda3_\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\andre\anaconda3_\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\andre\anaconda3_\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andre\anaconda3_\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\andre\anaconda3_\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Super_SD\sd_livepaint\SdPaint\Scripts\SdPaint.py", line 91, in send_request
    r = response.json()
  File "C:\Super_SD\sd_livepaint\SdPaint\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by hunter-meloche** [comment]
same error here too

**Comment by hunter-meloche** [comment]
ah just update sd-web-ui and controlnet
