### ISSUE TITLE
You have not selected any ControlNet Model.

### ISSUE THREAD

**Issue by Flynsarmy** [houseofsecrets/SdPaint#50]
After opening Start.bat for the first time and drawing I'm getting the following error:
```
Error running process: C:\Users\username\OneDrive\Desktop\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "C:\Users\username\OneDrive\Desktop\stable-diffusion-webui\modules\scripts.py", line 418, in process
    script.process(p, *script_args)
  File "C:\Users\username\OneDrive\Desktop\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1022, in process
    model_net = self.load_control_model(p, unet, unit.model, unit.low_vram)
  File "C:\Users\username\OneDrive\Desktop\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 685, in load_control_model
    model_net = self.build_control_model(p, unet, model, lowvram)
  File "C:\Users\username\OneDrive\Desktop\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 694, in build_control_model
    raise RuntimeError(f"You have not selected any ControlNet Model.")
RuntimeError: You have not selected any ControlNet Model.
```

I didn't change any settings in the webui - only checked the 'allow other script to control this extension' checkbox during installation:
![image](https://github.com/houseofsecrets/SdPaint/assets/334808/310cc505-a51a-49ef-baf1-3a5f5f2499b7)

I also haven't changed anything in SDPaint/config.json - it's all default.

**Comment by Flynsarmy** [comment]
> * check if http://127.0.0.1:7860/controlnet/model_list returns any models containing "inpaint" or "scribble"

I get the following:
```json
{
"model_list": [
"control_v11e_sd15_ip2p [c4bb465c]",
"control_v11e_sd15_shuffle [526bfdae]",
"control_v11f1e_sd15_tile [a371b31b]",
"control_v11f1p_sd15_depth [cfd03158]",
"control_v11p_sd15_canny [d14c016b]",
"control_v11p_sd15_inpaint [ebff9138]",
"control_v11p_sd15_lineart [43d4be0d]",
"control_v11p_sd15_mlsd [aca30ff0]",
"control_v11p_sd15_normalbae [316696f1]",
"control_v11p_sd15_openpose [cab727d4]",
"control_v11p_sd15_scribble [d4ba51ff]",
"control_v11p_sd15_seg [e1f51eb9]",
"control_v11p_sd15_softedge [a8575a2a]",
"control_v11p_sd15s2_lineart_anime [3825e83e]"
]
}
```
> * run SdPaint again
> * check if the newly created config.json contains at least one detected controlnet model

Here's the new config.json:
```json
{
    "interface_width": 1280,
    "interface_height": 720,
    "url": "http://127.0.0.1:7860",
    "autosave_seed": "true",
    "autosave_prompt": "true",
    "autosave_negative_prompt": "true",
    "autosave_images": "true",
    "autosave_images_max": 5,
    "preset_fields": [
        "hr_scale",
        "hr_upscaler",
        "denoising_strength"
    ],
    "cn_preset_fields": [
        "controlnet_model",
        "controlnet_weight",
        "controlnet_guidance_end"
    ],
    "hr_scales": [
        1.0,
        1.25,
        1.5,
        2
    ],
    "hr_upscalers": [
        "Latent (bicubic)",
        "R-ESRGAN 4x+"
    ],
    "denoising_strengths": [
        0.6,
        0.4,
        0.5
    ],
    "controlnet_weights": [
        0.6,
        1.0,
        1.6
    ],
    "controlnet_guidance_ends": [
        1.0,
        0.2,
        0.3
    ],
    "controlnet_models": [
        "control_v11p_sd15_scribble",
        "control_v11p_sd15_lineart",
        "control_v11p_sd15s2_lineart_anime"
    ],
    "detectors": [
        "lineart",
        "lineart_coarse",
        "pidinet_sketch",
        "pidinet_scribble"
    ],
    "samplers": [
        "DPM++ 2M Karras",
        "DDIM",
        "Euler",
        "Euler a",
        "DPM++ SDE Karras"
    ],
    "batch_sizes": [
        1,
        4,
        9,
        16
    ]
}
```

**Comment by Flynsarmy** [comment]
Got it working after closing and reopening Start.bat a few times.
