### ISSUE TITLE
KeyError: 'sd_model_checkpoint'

### ISSUE THREAD

**Issue by zemooo7** [houseofsecrets/SdPaint#62]
Traceback (most recent call last):
  File "d:\StableDiffusion\SdPaint\SdPaint.py", line 16, in <module>
    view = PygameView(img2img)
  File "d:\StableDiffusion\SdPaint\scripts\views\PygameView.py", line 76, in __init__
    self.state = State(img2img)
  File "d:\StableDiffusion\SdPaint\scripts\common\state.py", line 86, in __init__
    self.update_webui_config()
  File "d:\StableDiffusion\SdPaint\scripts\common\state.py", line 212, in update_webui_config
    self.render['checkpoint'] = self.configuration["webui_config"]['sd_model_checkpoint']
KeyError: 'sd_model_checkpoint'

can't find what the problem is, and there was no such error last week, I tried this all over again but the error still exists

**Comment by zemooo7** [comment]
Okay, just a typo, I typed a / at the end of the url, so when requesting, the url turns into 10.122.233.6:7860//controlnet/model_list, so do the other urls
