### ISSUE TITLE
everytime i use SDpaint, i get error

### ISSUE THREAD

**Issue by ppkppk8520** [houseofsecrets/SdPaint#8]
Exception in thread Thread-1 (send_request):
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\00etc\SdPaint-main\venv\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\xxx\miniconda3\envs\qwe\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\xxx\miniconda3\envs\qwe\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\xxx\miniconda3\envs\qwe\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\miniconda3\envs\qwe\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\xxx\miniconda3\envs\qwe\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "G:\stable-diffusion-webui\00etc\SdPaint-main\Scripts\SdPaint.py", line 91, in send_request
    r = response.json()
  File "G:\stable-diffusion-webui\00etc\SdPaint-main\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

i got same error when control_v11p_sd15_scribble.pth(yaml too) is in stable-diffusion-webui\extensions\sd-webui-controlnet\models and also stable-diffusion-webui\models\ControlNet

**Comment by houseofsecrets** [comment]
I think you need to update automatic1111 and controlnet.
Let me know if that fixed it
